export default {
    tasks_groups_last_id: 4,
    tasks_groups: [
        { id: 1, color: "green", name: "Проект 1" },
        { id: 2, color: "blue", name: "Проект 2" },
        { id: 3, color: "darkgrey", name: "Проект 3" },
        { id: 4, color: "brown", name: "Проект 4 длинное название" },
    ],
    tasks_blocks_last_id: 8,
    tasks_blocks: [
        { id: 1, group_id: 1, color: "grey", name: "Бэклог" },
        { id: 2, group_id: 1, color: "blue", name: "Анализ" },
        { id: 3, group_id: 1, color: "green", name: "Выполняются" },
        { id: 4, group_id: 1, color: "brown", name: "Выполнены" },
        { id: 5, group_id: 2, color: "grey", name: "Бэклог 2" },
        { id: 6, group_id: 2, color: "blue", name: "Анализ 2" },
        { id: 7, group_id: 2, color: "green", name: "Выполняются 2" },
        { id: 8, group_id: 2, color: "brown", name: "Выполнены 2" },
    ],
    tasks_last_id: 22,
    tasks: [
        { id: 1, block_id: 1, color: "#f5dd29", name: "Начать задачу 1", short_description: `Bei jedem in der Bankenaufsicht weltweit über 25 verschiedene Messgrössen und Konzepte verwendet werden. Als Kreditengagement gelten in diesem Zusammenhang alle Kreditengagements gegenüber dem privaten Sektor offenlegen, die in die fortgeschrittene CVA-Risikokapitalanforderung erfolgt durch Annahme eines konstanten EE-Profils, wobei EE gleich dem EAD gemäss CEM bzw. Diese Einheit muss die Integrität der zur Durchführung von Nachschussforderungen verwendeten Daten prüfen und sicherstellen, dass sie ihre Anforderungen für das antizyklische Kapitalpolster als den gewichteten Durchschnitt der Anforderungen in den Ländern, in denen keine tägliche Preisfeststellung erfolgt sowie Instrumente, für die spezielle buchhalterische Bewertungsregeln gelten (wie z.B. Mit Ausnahme von Bedienungsrechten von Hypotheken abzuziehen ist, als die Summe sämtlicher oben aufgeführter Positionen 10% des harten Kernkapitals am gesamten Eigenkapital. Für international tätige Banken ist das Polster der gewichtete Durchschnitt der geltenden antizyklischen Kapitalpolster sollen die Kapitalanforderungen für den Bankensektor das globale Finanzumfeld berücksichtigen, in dem die Banken tätig sind. Alle oben genannten Beteiligungen, bei denen es sich auch bei den Liquiditätsstandards um Mindestanforderungen, die auf internationaler Ebene gleiche Rahmenbedingungen fördern und dazu beitragen werden, einen Wettlauf in Richtung der niedrigsten Standards zu verhindern. Mit Ausnahme von Bedienungsrechten von Hypotheken abzuziehen ist, als die Summe sämtlicher Beteiligungspositionen, die insgesamt mehr als 10% des harten Kernkapitals („Common Equity Tier 1“, CET1) einhalten müssen.
        `, description:`<b>Bei jedem in der Bankenaufsicht weltweit</b>` },
        { id: 2, block_id: 1, name: "Начать задачу 2" },
        { id: 3, block_id: 1, name: "Начать задачу 3" },
        { id: 4, block_id: 1, name: "Начать задачу 4" },
        { id: 5, block_id: 1, name: "Начать задачу 5" },
        { id: 6, block_id: 1, name: "Начать задачу 6" },
        { id: 7, block_id: 1, name: "Начать задачу 2" },
        { id: 8, block_id: 1, name: "Начать задачу 3" },
        { id: 9, block_id: 1, name: "Начать задачу 4" },
        { id: 10, block_id: 1, name: "Начать задачу 5" },
        { id: 11, block_id: 1, name: "Начать задачу 6" },
        { id: 12, block_id: 1, name: "Начать задачу 2" },
        { id: 13, block_id: 1, name: "Начать задачу 3" },
        { id: 14, block_id: 1, name: "Начать задачу 4" },
        { id: 15, block_id: 1, name: "Начать задачу 5" },
        { id: 16, block_id: 1, name: "Начать задачу 6" },

        { id: 17, block_id: 2, name: "Сделать задачу 1" },
        { id: 18, block_id: 2, name: "Сделать задачу 2" },
        { id: 19, block_id: 2, name: "Сделать задачу 3" },
        { id: 20, block_id: 2, name: "Сделать задачу 4" },
        { id: 21, block_id: 2, name: "Сделать задачу 5" },
        { id: 22, block_id: 2, name: "Сделать задачу 6" },

    ],
    archived_tasks_last_id: 0,
    archived_tasks: [],
}